(deftheme mymymy
  "Created 2015-03-18.")

(custom-theme-set-variables
 'mymymy
 '(browse-url-browser-function (quote browse-url-default-macosx-browser))
 '(custom-safe-themes (quote ("8aebf25556399b58091e533e455dd50a6a9cba958cc4ebb0aab175863c25b9a4" "d677ef584c6dfc0697901a44b885cc18e206f05114c8a3b7fde674fce6180879" default)))
 '(flycheck-checkers (quote (ada-gnat asciidoc c/c++-clang c/c++-gcc c/c++-cppcheck cfengine chef-foodcritic coffee coffee-coffeelint coq css-csslint d-dmd elixir emacs-lisp emacs-lisp-checkdoc erlang eruby-erubis fortran-gfortran go-gofmt go-golint go-vet go-build go-test go-errcheck haml handlebars haskell-ghc haskell-hlint html-tidy javascript-jshint javascript-eslint javascript-gjslint json-jsonlint less lua perl perl-perlcritic php php-phpmd php-phpcs puppet-parser puppet-lint python-pylint python-flake8 python-pycompile r-lintr racket rpm-rpmlint rst rst-sphinx ruby-rubocop ruby-rubylint ruby ruby-jruby rust sass scala scala-scalastyle scss sh-bash sh-posix-dash sh-posix-bash sh-zsh sh-shellcheck slim tex-chktex tex-lacheck texinfo verilog-verilator xml-xmlstarlet xml-xmllint yaml-jsyaml yaml-ruby)))
 '(flycheck-pylintrc "~/.emacs.d/.pylintrc")
 '(flymake-allowed-file-name-masks (quote (("\\.py\\'" flymake-pyflakes-init))))
 '(header-date-format t)
 '(indent-tabs-mode t)
 '(make-header-hook (quote (header-file-name header-description header-author header-creation-date header-modification-date header-modification-author header-update-count header-commentary header-end-line)))
 '(org-directory "~/Dropbox/org")
 '(org-hide-emphasis-markers t)
 '(org-hide-leading-stars t)
 '(org-pretty-entities t)
 '(tool-bar-mode nil)
 '(ansi-color-names-vector ["#eee8d5" "#dc322f" "#859900" "#b58900" "#268bd2" "#d33682" "#2aa198" "#839496"])
 '(compilation-message-face (quote (quote default))))

(custom-theme-set-faces
 'mymymy
 '(flycheck-warning ((((supports :underline (:style wave)) (class color) (min-colors 89)) (:underline (:style wave :color "#b58900") :inherit unspecified)) (((class color) (min-colors 89)) (:foreground "#7B6000" :background "#DEB542" :weight bold :underline t))))
 '(font-lock-keyword-face ((((class color) (min-colors 89)) (:foreground "#859900" :weight bold))))
 '(font-lock-warning-face ((((class color) (min-colors 89)) (:foreground "#cb4b16" :weight bold :underline t))))
 '(semantic-highlight-func-current-tag-face ((t (:background "white"))))
 '(default ((t (:background "#fdf6e3" :foreground "#111111"))))
 '(shadow ((((class color) (min-colors 89)) (:foreground "#93a1a1"))))
 '(match ((((class color) (min-colors 89)) (:background "#eee8d5" :foreground "#586e75" :weight bold))))
 '(cursor ((((class color) (min-colors 89)) (:foreground "#fdf6e3" :background "#657b83" :inverse-video t))))
 '(mouse ((((class color) (min-colors 89)) (:foreground "#fdf6e3" :background "#657b83" :inverse-video t))))
 '(escape-glyph ((((class color) (min-colors 89)) (:foreground "#6c71c4"))))
 '(fringe ((((class color) (min-colors 89)) (:foreground "#93a1a1" :background "#fdf6e3"))))
 '(highlight ((((class color) (min-colors 89)) (:background "#eee8d5"))))
 '(link ((((class color) (min-colors 89)) (:foreground "#b58900" :underline t :weight bold))))
 '(link-visited ((((class color) (min-colors 89)) (:foreground "#b58900" :underline t :weight normal))))
 '(success ((((class color) (min-colors 89)) (:foreground "#859900"))))
 '(warning ((((class color) (min-colors 89)) (:foreground "#b58900"))))
 '(error ((((class color) (min-colors 89)) (:foreground "#cb4b16"))))
 '(lazy-highlight ((((class color) (min-colors 89)) (:foreground "#fdf6e3" :background "#b58900" :weight normal))))
 '(widget-field ((((class color) (min-colors 89)) (:background "#eee8d5"))))
 '(button ((t (:underline t))))
 '(compilation-column-number ((((class color) (min-colors 89)) (:inherit font-lock-doc-face :foreground "#2aa198" :underline nil))))
 '(compilation-error ((((class color) (min-colors 89)) (:inherit error :underline nil))))
 '(compilation-info ((((class color) (min-colors 89)) (:foreground "#93a1a1" :underline nil :bold nil))))
 '(compilation-line-number ((((class color) (min-colors 89)) (:foreground "#859900" :underline nil))))
 '(compilation-warning ((((class color) (min-colors 89)) (:inherit warning :underline nil))))
 '(compilation-mode-line-exit ((((class color) (min-colors 89)) (:inherit compilation-info :foreground "#859900" :weight bold))))
 '(compilation-mode-line-fail ((((class color) (min-colors 89)) (:inherit compilation-error :foreground "#dc322f" :weight bold))))
 '(compilation-mode-line-run ((((class color) (min-colors 89)) (:foreground "#cb4b16" :weight bold))))
 '(diary ((((class color) (min-colors 89)) (:foreground "#b58900"))))
 '(completions-annotations ((t (:foreground "#93a1a1"))))
 '(isearch ((((class color) (min-colors 89)) (:foreground "#fdf6e3" :background "#d33682" :weight normal))))
 '(isearch-fail ((((class color) (min-colors 89)) (:foreground "#dc322f" :background "#fdf6e3" :bold t))))
 '(menu ((((class color) (min-colors 89)) (:foreground "#657b83" :background "#fdf6e3"))))
 '(minibuffer-prompt ((((class color) (min-colors 89)) (:foreground "#657b83"))))
 '(mode-line ((((class color) (min-colors 89)) (:inverse-video unspecified :overline "#eee8d5" :underline "#cccec4" :foreground "#657b83" :background "#eee8d5" :box (:line-width 1 :color "#eee8d5" :style unspecified)))))
 '(mode-line-buffer-id ((((class color) (min-colors 89)) (:foreground "#586e75" :weight bold))))
 '(mode-line-inactive ((((class color) (min-colors 89)) (:inverse-video unspecified :overline "#eee8d5" :underline "#cccec4" :foreground "#93a1a1" :background "#fdf6e3" :box (:line-width 1 :color "#fdf6e3" :style unspecified)))))
 '(header-line ((((class color) (min-colors 89)) (:inverse-video unspecified :overline nil :underline "#eee8d5" :foreground "#657b83" :background "#fdf6e3" :box (:line-width 2 :color "#fdf6e3" :style unspecified)))))
 '(region ((((class color) (min-colors 89)) (:foreground "#fdf6e3" :background "#586e75"))))
 '(secondary-selection ((((class color) (min-colors 89)) (:background "#eee8d5"))))
 '(trailing-whitespace ((((class color) (min-colors 89)) (:background "#dc322f"))))
 '(vertical-border ((((class color) (min-colors 89)) (:foreground "#cccec4"))))
 '(font-lock-builtin-face ((((class color) (min-colors 89)) (:foreground "#657b83" :weight bold :slant normal))))
 '(font-lock-comment-delimiter-face ((((class color) (min-colors 89)) (:foreground "#93a1a1" :slant normal))))
 '(font-lock-comment-face ((((class color) (min-colors 89)) (:foreground "#93a1a1"))))
 '(font-lock-constant-face ((((class color) (min-colors 89)) (:foreground "#268bd2" :weight bold))))
 '(font-lock-doc-face ((((class color) (min-colors 89)) (:foreground "#2aa198" :slant normal))))
 '(font-lock-function-name-face ((((class color) (min-colors 89)) (:foreground "#268bd2"))))
 '(font-lock-negation-char-face ((((class color) (min-colors 89)) (:foreground "#b58900" :weight bold))))
 '(font-lock-preprocessor-face ((((class color) (min-colors 89)) (:foreground "#268bd2"))))
 '(font-lock-regexp-grouping-construct ((((class color) (min-colors 89)) (:foreground "#b58900" :weight bold))))
 '(font-lock-regexp-grouping-backslash ((((class color) (min-colors 89)) (:foreground "#859900" :weight bold))))
 '(font-lock-string-face ((((class color) (min-colors 89)) (:foreground "#2aa198"))))
 '(font-lock-type-face ((((class color) (min-colors 89)) (:foreground "#b58900"))))
 '(font-lock-variable-name-face ((((class color) (min-colors 89)) (:foreground "#268bd2"))))
 '(company-template-field ((((class color) (min-colors 89)) (:background "#b58900" :foreground "#eee8d5"))))
 '(company-tooltip ((((class color) (min-colors 89)) (:background "#eee8d5" :foreground "#2aa198"))))
 '(company-tooltip-selection ((((class color) (min-colors 89)) (:background "#69CABF" :foreground "#00736F"))))
 '(company-tooltip-mouse ((((class color) (min-colors 89)) (:background "#00736F" :foreground "#69CABF"))))
 '(company-tooltip-common ((((class color) (min-colors 89)) (:foreground "#586e75" :underline t))))
 '(company-tooltip-common-selection ((((class color) (min-colors 89)) (:foreground "#586e75" :underline t))))
 '(company-tooltip-annotation ((((class color) (min-colors 89)) (:foreground "#586e75" :background "#eee8d5"))))
 '(company-scrollbar-fg ((((class color) (min-colors 89)) (:foreground "#fdf6e3" :background "#657b83"))))
 '(company-scrollbar-bg ((((class color) (min-colors 89)) (:background "#eee8d5" :foreground "#2aa198"))))
 '(company-preview ((((class color) (min-colors 89)) (:background "#eee8d5" :foreground "#2aa198"))))
 '(company-preview-common ((((class color) (min-colors 89)) (:foreground "#586e75" :underline t))))
 '(custom-face-tag ((((class color) (min-colors 89)) (:inherit variable-pitch :height 1.2 :foreground "#6c71c4" :weight normal))))
 '(custom-variable-tag ((((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#2aa198" :height 1.2))))
 '(custom-comment-tag ((((class color) (min-colors 89)) (:foreground "#93a1a1"))))
 '(custom-group-tag ((((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#268bd2" :height 1.2))))
 '(custom-group-tag-1 ((((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#dc322f" :height 1.2))))
 '(custom-state ((((class color) (min-colors 89)) (:foreground "#859900"))))
 '(custom-button ((((class color) (min-colors 89)) (:background "#eee8d5" :foreground "#586e75" :box (:line-width 2 :style released-button)))))
 '(custom-button-mouse ((((class color) (min-colors 89)) (:background "#93a1a1" :foreground "#eee8d5" :box (:line-width 2 :style released-button)))))
 '(custom-button-pressed ((((class color) (min-colors 89)) (:background "#93a1a1" :foreground "#586e75" :box (:line-width 2 :style pressed-button)))))
 '(custom-button-unraised ((((class color) (min-colors 89)) (:inherit underline))))
 '(custom-button-pressed-unraised ((((class color) (min-colors 89)) (:inherit custom-button-unraised :foreground "#d33682"))))
 '(flymake-errline ((((supports :underline (:style wave)) (class color) (min-colors 89)) (:underline (:style wave :color "#dc322f") :inherit unspecified :foreground unspecified :background unspecified)) (((class color) (min-colors 89)) (:foreground "#990A1B" :background "#FF6E64" :weight bold :underline t))))
 '(flymake-warnline ((((supports :underline (:style wave)) (class color) (min-colors 89)) (:underline (:style wave :color "#b58900") :inherit unspecified :foreground unspecified :background unspecified)) (((class color) (min-colors 89)) (:foreground "#7B6000" :background "#DEB542" :weight bold :underline t))))
 '(flycheck-error ((((supports :underline (:style wave)) (class color) (min-colors 89)) (:underline (:style wave :color "#dc322f") :inherit unspecified)) (((class color) (min-colors 89)) (:foreground "#990A1B" :background "#FF6E64" :weight bold :underline t))))
 '(flycheck-info ((((supports :underline (:style wave)) (class color) (min-colors 89)) (:underline (:style wave :color "#268bd2") :inherit unspecified)) (((class color) (min-colors 89)) (:foreground "#00629D" :background "#69B7F0" :weight bold :underline t))))
 '(flycheck-fringe-error ((((class color) (min-colors 89)) (:foreground "#990A1B" :background "#FF6E64" :weight bold))))
 '(flycheck-fringe-warning ((((class color) (min-colors 89)) (:foreground "#7B6000" :background "#DEB542" :weight bold))))
 '(flycheck-fringe-info ((((class color) (min-colors 89)) (:foreground "#00629D" :background "#69B7F0" :weight bold))))
 '(ido-first-match ((((class color) (min-colors 89)) (:foreground "#b58900" :weight normal))))
 '(ido-only-match ((((class color) (min-colors 89)) (:foreground "#fdf6e3" :background "#b58900" :weight normal))))
 '(ido-subdir ((((class color) (min-colors 89)) (:foreground "#268bd2"))))
 '(ido-incomplete-regexp ((((class color) (min-colors 89)) (:foreground "#dc322f" :weight bold))))
 '(ido-indicator ((((class color) (min-colors 89)) (:background "#dc322f" :foreground "#fdf6e3" :width condensed))))
 '(ido-virtual ((((class color) (min-colors 89)) (:foreground "#2aa198"))))
 '(info-title-1 ((((class color) (min-colors 89)) (:foreground "#586e75" :weight bold))))
 '(info-title-2 ((((class color) (min-colors 89)) (:foreground "#586e75" :weight bold))))
 '(info-title-3 ((((class color) (min-colors 89)) (:weight bold))))
 '(info-title-4 ((((class color) (min-colors 89)) (:weight bold))))
 '(info-node ((((class color) (min-colors 89)) (:foreground "#586e75" :slant italic :weight bold))))
 '(info-header-node ((((class color) (min-colors 89)) (:inherit info-node))))
 '(info-header-xref ((((class color) (min-colors 89)) (:inherit info-xref))))
 '(info-index-match ((((class color) (min-colors 89)) (:inherit match))))
 '(info-menu-header ((((class color) (min-colors 89)) (:inherit variable-pitch :weight bold))))
 '(info-menu-star ((((class color) (min-colors 89)) (:foreground "#cb4b16"))))
 '(info-xref ((((class color) (min-colors 89)) (:inherit link))))
 '(info-xref-visited ((((class color) (min-colors 89)) (:inherit (link-visited info-xref)))))
 '(org-agenda-structure ((((class color) (min-colors 89)) (:foreground "#586e75" :background "#eee8d5" :weight bold :slant normal :inverse-video nil :height 1.1 :underline nil :box (:line-width 2 :color "#fdf6e3")))))
 '(org-agenda-calendar-event ((((class color) (min-colors 89)) (:foreground "#586e75"))))
 '(org-agenda-calendar-sexp ((((class color) (min-colors 89)) (:foreground "#657b83" :slant italic))))
 '(org-agenda-date ((((class color) (min-colors 89)) (:foreground "#93a1a1" :background "#fdf6e3" :weight normal :box (:line-width 2 :color "#fdf6e3") :inverse-video nil :overline nil :slant normal :height 1.0))))
 '(org-agenda-date-weekend ((((class color) (min-colors 89)) (:inherit org-agenda-date :inverse-video nil :background unspecified :foreground "#93a1a1" :weight unspecified :underline t :overline nil :box unspecified))))
 '(org-agenda-date-today ((((class color) (min-colors 89)) (:inherit org-agenda-date :inverse-video t :weight bold :underline unspecified :overline nil :box unspecified :foreground "#268bd2" :background "#fdf6e3"))))
 '(org-agenda-done ((((class color) (min-colors 89)) (:foreground "#93a1a1" :slant italic))))
 '(org-archived ((((class color) (min-colors 89)) (:foreground "#93a1a1" :weight normal))))
 '(org-block ((((class color) (min-colors 89)) (:foreground "#93a1a1"))))
 '(org-block-begin-line ((((class color) (min-colors 89)) (:foreground "#93a1a1" :slant italic))))
 '(org-checkbox ((((class color) (min-colors 89)) (:background "#fdf6e3" :foreground "#657b83" :box (:line-width 1 :style released-button)))))
 '(org-code ((((class color) (min-colors 89)) (:foreground "#93a1a1"))))
 '(org-date ((((class color) (min-colors 89)) (:foreground "#268bd2" :underline t))))
 '(org-done ((((class color) (min-colors 89)) (:weight bold :foreground "#859900"))))
 '(org-ellipsis ((((class color) (min-colors 89)) (:foreground "#93a1a1"))))
 '(org-formula ((((class color) (min-colors 89)) (:foreground "#b58900"))))
 '(org-headline-done ((((class color) (min-colors 89)) (:foreground "#859900"))))
 '(org-hide ((((class color) (min-colors 89)) (:foreground "#fdf6e3"))))
 '(org-level-1 ((((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#cb4b16" :height 1.3))))
 '(org-level-2 ((((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#859900" :height 1.2))))
 '(org-level-3 ((((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#268bd2" :height 1.15))))
 '(org-level-4 ((((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#b58900" :height 1.1))))
 '(org-level-5 ((((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#2aa198"))))
 '(org-level-6 ((((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#859900"))))
 '(org-level-7 ((((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#dc322f"))))
 '(org-level-8 ((((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#268bd2"))))
 '(org-link ((((class color) (min-colors 89)) (:foreground "#b58900" :underline t))))
 '(org-sexp-date ((((class color) (min-colors 89)) (:foreground "#6c71c4"))))
 '(org-scheduled ((((class color) (min-colors 89)) (:foreground "#859900"))))
 '(org-scheduled-previously ((((class color) (min-colors 89)) (:foreground "#2aa198"))))
 '(org-scheduled-today ((((class color) (min-colors 89)) (:foreground "#268bd2" :weight normal))))
 '(org-special-keyword ((((class color) (min-colors 89)) (:foreground "#93a1a1" :weight bold))))
 '(org-table ((((class color) (min-colors 89)) (:foreground "#859900"))))
 '(org-tag ((((class color) (min-colors 89)) (:weight bold))))
 '(org-time-grid ((((class color) (min-colors 89)) (:foreground "#93a1a1"))))
 '(org-todo ((((class color) (min-colors 89)) (:foreground "#2aa198" :weight bold))))
 '(org-upcoming-deadline ((((class color) (min-colors 89)) (:foreground "#b58900" :weight normal :underline nil))))
 '(org-warning ((((class color) (min-colors 89)) (:foreground "#cb4b16" :weight normal :underline nil))))
 '(org-agenda-dimmed-todo-face ((((class color) (min-colors 89)) (:foreground "#93a1a1"))))
 '(org-agenda-restriction-lock ((((class color) (min-colors 89)) (:background "#b58900"))))
 '(org-clock-overlay ((((class color) (min-colors 89)) (:background "#b58900"))))
 '(org-column ((((class color) (min-colors 89)) (:background "#eee8d5" :strike-through nil :underline nil :slant normal :weight normal :inherit default))))
 '(org-column-title ((((class color) (min-colors 89)) (:background "#eee8d5" :underline t :weight bold))))
 '(org-date-selected ((((class color) (min-colors 89)) (:foreground "#dc322f" :inverse-video t))))
 '(org-document-info ((((class color) (min-colors 89)) (:foreground "#657b83"))))
 '(org-document-title ((((class color) (min-colors 89)) (:foreground "#586e75" :weight bold :height 1.3))))
 '(org-drawer ((((class color) (min-colors 89)) (:foreground "#2aa198"))))
 '(org-footnote ((((class color) (min-colors 89)) (:foreground "#d33682" :underline t))))
 '(org-mode-line-clock-overrun ((((class color) (min-colors 89)) (:inherit mode-line :background "#dc322f"))))
 '(outline-1 ((((class color) (min-colors 89)) (:inherit org-level-1 :height 1.3))))
 '(outline-2 ((((class color) (min-colors 89)) (:inherit org-level-2 :height 1.2))))
 '(outline-3 ((((class color) (min-colors 89)) (:inherit org-level-3 :height 1.15))))
 '(outline-4 ((((class color) (min-colors 89)) (:inherit org-level-4 :height 1.1))))
 '(outline-5 ((((class color) (min-colors 89)) (:inherit org-level-5))))
 '(outline-6 ((((class color) (min-colors 89)) (:inherit org-level-6))))
 '(outline-7 ((((class color) (min-colors 89)) (:inherit org-level-7))))
 '(outline-8 ((((class color) (min-colors 89)) (:inherit org-level-8))))
 '(show-paren-match ((((class color) (min-colors 89)) (:foreground "#d33682" :background unspecified :weight bold))))
 '(show-paren-mismatch ((((class color) (min-colors 89)) (:foreground "#eee8d5" :background "#dc322f" :weight bold))))
 '(speedbar-button-face ((((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#93a1a1"))))
 '(speedbar-directory-face ((((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#268bd2"))))
 '(speedbar-file-face ((((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#657b83"))))
 '(speedbar-highlight-face ((((class color) (min-colors 89)) (:inherit variable-pitch :background "#eee8d5"))))
 '(speedbar-selected-face ((((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#b58900" :underline t))))
 '(speedbar-separator-face ((((class color) (min-colors 89)) (:inherit variable-pitch :background "#268bd2" :foreground "#fdf6e3" :overline "#69CABF"))))
 '(speedbar-tag-face ((((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#859900"))))
 '(tooltip ((((class color) (min-colors 89)) (:background "#DEB542" :foreground "#7B6000" :inherit variable-pitch)))))

(provide-theme 'mymymy)
